import { useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, TextInput, View } from "react-native";
import { Handshake, MessageSquareText, X } from "lucide-react-native";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { SafeAreaView } from "react-native-safe-area-context";
import { apiQueryKeys, dealDraftSchema, dealStageLabels, marketingChannelLabels, marketingChannels, nextDealStages, nextPresentationStatuses, presentationDraftSchema, presentationStatusLabels, type MarketingChannel } from "@spherepath/shared";
import { useSession } from "@/features/auth/resources/session";
import { listContacts } from "@/features/contacts/resources/contacts";
import type { ListingRecord } from "@/features/listings/resources/listings";
import { SpCard } from "@/shared/ui/SpCard";
import { SpText } from "@/shared/ui/SpText";
import { radius, space } from "@/shared/ui/tokens.generated";
import { useSpTheme } from "@/shared/ui/theme";
import { getClosingOverview, moveDeal, movePresentation, saveDeal, savePresentation } from "../resources/closing";

const messageFrom = (error: unknown) => error instanceof Error ? error.message : "Kapama işlemi tamamlanamadı.";
export function ClosingSection({ listings }: { listings: ListingRecord[] }) {
  const theme = useSpTheme(); const { session } = useSession(); const queryClient = useQueryClient(); const query = useQuery({ queryKey: apiQueryKeys.closing, queryFn: getClosingOverview }); const contactsQuery = useQuery({ queryKey: apiQueryKeys.contacts, queryFn: listContacts }); const contacts = contactsQuery.data ?? []; const available = listings.filter((item) => item.status === "active" || item.status === "reserved");
  const [mode, setMode] = useState<"presentation" | "deal" | null>(null); const [listingId, setListingId] = useState(""); const [contactId, setContactId] = useState(""); const [channel, setChannel] = useState<MarketingChannel>("whatsapp"); const [message, setMessage] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null); const selectedListing = listingId || available[0]?.id || ""; const selectedContact = contactId || contacts[0]?.id || "";
  const choice = (selected: boolean) => [styles.choice, { backgroundColor: selected ? theme.deedBg : theme.background, borderColor: selected ? theme.deed : theme.line }]; const inputStyle = [styles.input, { color: theme.textPrimary, backgroundColor: theme.background, borderColor: theme.line }];
  async function refresh() { await Promise.all([queryClient.invalidateQueries({ queryKey: apiQueryKeys.closing }), queryClient.invalidateQueries({ queryKey: apiQueryKeys.todayOverview })]); }
  async function create() { if (!session || !mode) return; setPending(true); setError(null); try { if (mode === "presentation") { const parsed = presentationDraftSchema.safeParse({ listingId: selectedListing, contactId: selectedContact, channel, message }); if (!parsed.success) throw new Error(parsed.error.issues[0]?.message ?? "Sunum bilgilerini kontrol et."); await savePresentation(session, parsed.data); } else { const parsed = dealDraftSchema.safeParse({ listingId: selectedListing, buyerContactId: selectedContact || null }); if (!parsed.success) throw new Error("İşlem bilgilerini kontrol et."); await saveDeal(session, parsed.data); } setMode(null); setMessage(""); await refresh(); } catch (nextError) { setError(messageFrom(nextError)); } finally { setPending(false); } }
  async function advancePresentation(id: string, status: Parameters<typeof nextPresentationStatuses>[0]) { if (!session) return; const next = nextPresentationStatuses(status)[0]; if (!next) return; setPending(true); try { await movePresentation(session, { presentationId: id, toStatus: next }); await refresh(); } catch (nextError) { setError(messageFrom(nextError)); } finally { setPending(false); } }
  async function advanceDeal(id: string, stage: Parameters<typeof nextDealStages>[0]) { if (!session) return; const next = nextDealStages(stage)[0]; if (!next || next === "offer" || next === "lost") { setError("Teklif ve kayıp ayrıntıları web görünümünden kaydedilebilir."); return; } setPending(true); try { await moveDeal(session, { dealId: id, toStage: next, offerAmount: null, currency: null, lostReason: null }); await refresh(); } catch (nextError) { setError(messageFrom(nextError)); } finally { setPending(false); } }
  return <View style={styles.section}><View style={styles.heading}><SpText variant="eyebrow" color="deed">PAZARLAMA VE KAPAMA</SpText><SpText variant="title">Sunumlar ve işlemler</SpText></View><View style={styles.actions}><Pressable disabled={!available.length || !contacts.length} onPress={() => setMode("presentation")} style={[styles.action, { borderColor: theme.line }]}><MessageSquareText color={theme.textSecondary} size={17} /><SpText variant="bodySmall">Sunum</SpText></Pressable><Pressable disabled={!available.length} onPress={() => setMode("deal")} style={[styles.action, { borderColor: theme.line }]}><Handshake color={theme.textSecondary} size={17} /><SpText variant="bodySmall">İşlem</SpText></Pressable></View>{error ? <View style={[styles.error, { backgroundColor: theme.askBg }]}><SpText color="ask">{error}</SpText></View> : null}{query.data?.presentations.map((item) => <SpCard key={item.id} style={styles.card}><SpText variant="title">{item.contactName}</SpText><SpText color="secondary">{item.listingAddress} · {presentationStatusLabels[item.status]}</SpText>{nextPresentationStatuses(item.status).length ? <Pressable disabled={pending} onPress={() => void advancePresentation(item.id, item.status)} style={[styles.action, { borderColor: theme.line }]}><SpText variant="bodySmall">{presentationStatusLabels[nextPresentationStatuses(item.status)[0]!]}</SpText></Pressable> : null}</SpCard>)}{query.data?.deals.map((item) => <SpCard key={item.id} style={styles.card}><SpText variant="title">{item.buyerContactName ?? "Alıcı daha sonra"}</SpText><SpText color="secondary">{item.listingAddress} · {dealStageLabels[item.stage]}</SpText>{nextDealStages(item.stage).length ? <Pressable onPress={() => void advanceDeal(item.id, item.stage)} style={[styles.action, { borderColor: theme.line }]}><SpText variant="bodySmall">Aşamayı ilerlet</SpText></Pressable> : null}</SpCard>)}
  <Modal animationType="slide" presentationStyle="pageSheet" visible={Boolean(mode)} onRequestClose={() => setMode(null)}><SafeAreaView style={[styles.safe, { backgroundColor: theme.card }]}><ScrollView contentContainerStyle={styles.form}><View style={styles.sheetHeader}><View><SpText variant="eyebrow" color="deed">KAPAMA AKIŞI</SpText><SpText variant="hero">{mode === "presentation" ? "Sunum taslağı" : "İşlem başlat"}</SpText></View><Pressable onPress={() => setMode(null)} style={[styles.icon, { borderColor: theme.line }]}><X color={theme.textSecondary} size={20} /></Pressable></View><SpText variant="title">Portföy</SpText><View style={styles.choices}>{available.map((item) => <Pressable key={item.id} onPress={() => setListingId(item.id)} style={choice(selectedListing === item.id)}><SpText variant="bodySmall" color={selectedListing === item.id ? "deed" : "secondary"}>{item.propertySummary.address}</SpText></Pressable>)}</View><SpText variant="title">İlgili kişi</SpText><View style={styles.choices}>{contacts.map((item) => <Pressable key={item.id} onPress={() => setContactId(item.id)} style={choice(selectedContact === item.id)}><SpText variant="bodySmall" color={selectedContact === item.id ? "deed" : "secondary"}>{item.fullName ?? item.label}</SpText></Pressable>)}</View>{mode === "presentation" ? <><SpText variant="title">Kanal</SpText><View style={styles.choices}>{marketingChannels.map((item) => <Pressable key={item} onPress={() => setChannel(item)} style={choice(channel === item)}><SpText variant="bodySmall" color={channel === item ? "deed" : "secondary"}>{marketingChannelLabels[item]}</SpText></Pressable>)}</View><SpText variant="title">Mesaj</SpText><TextInput multiline style={[inputStyle, styles.multiline]} value={message} onChangeText={setMessage} /><View style={[styles.hint, { backgroundColor: theme.deedBg }]}><SpText color="deed" variant="bodySmall">Gönderim dış uygulamadan sonra ayrıca onaylanır.</SpText></View></> : null}{error ? <View style={[styles.error, { backgroundColor: theme.askBg }]}><SpText color="ask">{error}</SpText></View> : null}<Pressable disabled={pending} onPress={() => void create()} style={[styles.primary, { backgroundColor: theme.ask }]}><SpText style={{ color: theme.onAsk }}>{pending ? "Kaydediliyor…" : "Kaydet"}</SpText></Pressable></ScrollView></SafeAreaView></Modal></View>;
}
const styles = StyleSheet.create({ safe: { flex: 1 }, section: { gap: space.md, paddingTop: space.xl, borderTopWidth: StyleSheet.hairlineWidth }, heading: { gap: space.xs }, actions: { flexDirection: "row", gap: space.sm }, action: { minHeight: 42, flex: 1, borderWidth: StyleSheet.hairlineWidth, borderRadius: radius.md, flexDirection: "row", justifyContent: "center", alignItems: "center", gap: space.sm, paddingHorizontal: space.sm }, card: { gap: space.sm }, error: { padding: space.md, borderRadius: radius.md }, form: { padding: space.xl, paddingBottom: space["5xl"], gap: space.md }, sheetHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" }, icon: { width: 44, height: 44, borderRadius: radius.md, borderWidth: StyleSheet.hairlineWidth, alignItems: "center", justifyContent: "center" }, choices: { flexDirection: "row", flexWrap: "wrap", gap: space.sm }, choice: { minHeight: 40, borderRadius: radius.sm, borderWidth: StyleSheet.hairlineWidth, justifyContent: "center", paddingHorizontal: space.md }, input: { minHeight: 50, borderRadius: radius.md, borderWidth: StyleSheet.hairlineWidth, padding: space.md, fontFamily: "Karla_400Regular", fontSize: 16 }, multiline: { minHeight: 100, textAlignVertical: "top" }, hint: { padding: space.md, borderRadius: radius.md }, primary: { minHeight: 50, borderRadius: radius.md, alignItems: "center", justifyContent: "center" } });
