import { expect, test } from "@playwright/test";
import { deleteApp, initializeApp } from "firebase/app";
import { connectAuthEmulator, getAuth, signInWithEmailAndPassword } from "firebase/auth";
import { connectFunctionsEmulator, getFunctions, httpsCallable } from "firebase/functions";

test("arsa talebi eşleşir, karşı teklif korunur ve satıcı görüşmesinden alıcıya öğlen takibi atanır", async ({ page }, info) => {
  const suffix = `${info.project.name}-${Date.now()}`;
  const email = `negotiation-${suffix}@example.test`;
  await page.goto("/");
  await page.getByRole("button", { name: "Yeni misin? Çalışma alanı oluştur" }).click();
  await page.getByLabel("Ad soyad").fill("Senaryo Danışmanı");
  await page.getByLabel("E-posta").fill(email);
  await page.getByLabel("Şifre").fill("Test-Advisor-2026!");
  await page.getByRole("button", { name: "Hesap oluştur" }).click();
  await expect(page.getByRole("heading", { name: "İlk işinle başla" })).toBeVisible();

  const app = initializeApp({ apiKey: "demo-key", projectId: "spherepath-96ecd" }, suffix);
  const auth = getAuth(app); connectAuthEmulator(auth, "http://127.0.0.1:9099", { disableWarnings: true });
  const functions = getFunctions(app, "europe-west8"); connectFunctionsEmulator(functions, "127.0.0.1", 5001);
  await signInWithEmailAndPassword(auth, email, "Test-Advisor-2026!");
  let seq = 0;
  const call = async <T,>(endpoint: string, data: unknown): Promise<T> => (await httpsCallable(functions, endpoint)({ data, requestId: `${suffix}-r-${++seq}`, commandId: `${suffix}-c-${seq}` })).data as T;
  const seller = (await call<{ contact: { id: string } }>("createContact", { fullName: "Anıl Emene", source: "in_person", phone: "", metAtPlace: "", role: "seller" })).contact;
  const buyer = (await call<{ contact: { id: string } }>("createContact", { fullName: "Melis Şaşmaz", source: "in_person", phone: "", metAtPlace: "", role: "buyer" })).contact;
  try {
    await page.goto(`/listings?action=add-listing&ownerContactId=${seller.id}`);
    let dialog = page.getByRole("dialog");
    await dialog.getByLabel("Adres", { exact: true }).fill("Kadıovacık 620 m² arsa");
    await dialog.getByLabel("Bölge", { exact: true }).fill("Kadıovacık");
    await dialog.getByRole("combobox", { name: "Mülk türü", exact: true }).selectOption("land");
    await expect(dialog.getByLabel("Oda", { exact: true })).toHaveCount(0);
    await expect(dialog.getByRole("button", { name: "Asansörsüz", exact: true })).toHaveCount(0);
    await dialog.getByLabel("Arsa alanı m²", { exact: true }).fill("620");
    await dialog.getByRole("combobox", { name: "Yetki", exact: true }).selectOption("verbal");
    await dialog.getByRole("textbox", { name: /Fiyat.*TRY/ }).fill("5000000");
    await dialog.getByRole("button", { name: "Yetkiyi ve portföyü oluştur" }).click();
    await expect(dialog).toBeHidden();
    await expect(page.getByText(/Hazırlanan: 1.*5.000.000/)).toBeVisible();

    await page.goto(`/opportunities?create=1&contactId=${buyer.id}`);
    dialog = page.getByRole("dialog");
    await expect(dialog.getByRole("combobox", { name: "Fırsat türü", exact: true })).toHaveValue("buyer_requirement");
    await dialog.getByLabel("Aranan bölgeler").fill("Kadıovacık");
    await dialog.getByRole("combobox", { name: "Aranan mülk türü", exact: true }).selectOption("land");
    await dialog.getByRole("combobox", { name: "Sonraki adım", exact: true }).selectOption("appointment");
    await dialog.getByRole("button", { name: "Yarın öğlen", exact: true }).click();
    await dialog.getByRole("button", { name: "Fırsatı oluştur", exact: true }).click();
    await expect(dialog.getByRole("heading", { name: "Melis Şaşmaz", exact: true })).toBeVisible();
    await expect(dialog.getByRole("heading", { name: "Bu talebe uygun portföyler" })).toBeVisible();
    await expect(dialog).toContainText("Kadıovacık 620 m² arsa");
    await expect(dialog).toContainText("Bilgi eksik; bilinen kriterlerde çelişki yok.");
    await dialog.getByRole("button", { name: "Bu portföye ilgiyi kaydet", exact: true }).click();
    await dialog.getByLabel("İlgi / talep açıklaması", { exact: true }).fill("Melis bu arsaya talip oldu.");
    await dialog.getByRole("button", { name: "Yarın öğlen", exact: true }).click();
    await dialog.getByRole("button", { name: "İlgiyi ve takibi kaydet", exact: true }).click();
    await expect(dialog).toContainText("Mülk ilgisi işleme bağlandı.");
    await dialog.getByRole("button", { name: "Kapat", exact: true }).click();
    await expect(page.locator(".work-row").filter({ hasText: "Melis Şaşmaz" })).toBeVisible();

    await page.goto("/contacts");
    const contactRow = page.locator(".contact-table-row").filter({ hasText: "Melis Şaşmaz" });
    await expect(contactRow).toBeVisible();
    await expect(contactRow).toContainText("yarın 12:00");
    await expect(contactRow).not.toContainText("Sonraki adım belirlenmedi");
    await page.goto(`/contacts/__contact__?contactId=${buyer.id}`);
    await page.getByRole("button", { name: "Tamamla veya ertele" }).click();
    dialog = page.getByRole("dialog");
    await dialog.getByRole("button", { name: /Ertele Yeni tarih/ }).click();
    await expect(dialog.getByRole("combobox", { name: "Yeni aksiyon", exact: true })).toHaveValue("appointment");
    await expect(dialog.locator('input[type="datetime-local"]')).toHaveValue(/T12:00$/);
    await dialog.locator(".quick-date-trigger").click();
    await dialog.getByLabel("Saat", { exact: true }).fill("13:30");
    await dialog.getByRole("button", { name: "Tarih ve saati uygula" }).click();
    await expect(dialog.locator('input[type="datetime-local"]')).toHaveValue(/T13:30$/);
    await dialog.getByRole("button", { name: "Kapat", exact: true }).click();

    await page.goto("/opportunities#closing");
    await page.getByRole("button", { name: "Teklif / karşı teklif kaydet", exact: true }).click();
    dialog = page.getByRole("dialog");
    await dialog.getByRole("textbox", { name: "Teklif TRY", exact: true }).fill("4500000");
    await dialog.getByLabel("Doğrulama notu").fill("Melis 4.500.000 TL teklif etti.");
    await dialog.getByRole("button", { name: "Aşamayı kaydet" }).click();
    await expect(dialog).toBeHidden();
    await expect(page.getByText(/Alıcı teklifi:.*4.500.000/)).toBeVisible();

    await page.goto(`/capture?contactId=${seller.id}`);
    await page.getByRole("tab", { name: "Manuel yaz", exact: true }).click();
    await page.getByLabel("Kısa sonuç", { exact: true }).fill("4,5 milyon teklif iletildi. Anıl 4,8 milyon karşı teklif verdi. Melis ile yarın öğlen randevu planlanacak.");
    await page.getByRole("combobox", { name: "İlgili işlem · varsa", exact: true }).selectOption({ index: 1 });
    await page.getByLabel("Görüşmedeki teklif tutarı · varsa").fill("4800000");
    await page.getByRole("combobox", { name: "Teklifi veren taraf", exact: true }).selectOption("seller");
    await page.getByRole("combobox", { name: "Aksiyon", exact: true }).selectOption("appointment");
    try { await page.getByRole("button", { name: "Yarın öğlen", exact: true }).click(); } catch (error) {
      await info.attach("date-layout", { contentType: "application/json", body: JSON.stringify(await page.evaluate(() => ({ width: innerWidth, height: innerHeight, scrollX, scrollY, documentWidth: document.documentElement.scrollWidth, viewport: visualViewport ? { width: visualViewport.width, height: visualViewport.height, offsetLeft: visualViewport.offsetLeft, offsetTop: visualViewport.offsetTop, scale: visualViewport.scale } : null, elements: [...document.querySelectorAll(".quick-date-options button, .quick-date-control, .sidebar")].map((el) => { const rect = el.getBoundingClientRect(); return { text: el.textContent, rect: rect.toJSON(), covering: document.elementFromPoint(rect.x + rect.width / 2, rect.y + rect.height / 2)?.outerHTML.slice(0, 300) }; }) }))) });
      throw error;
    }
    await page.getByRole("button", { name: "Anıl Emene için kaydet", exact: true }).click();
    await expect(page.getByRole("heading", { name: "Anıl Emene için temas kaydedildi" })).toBeVisible();
    await expect(page.getByText(/Sonraki adım \(Melis Şaşmaz\)/)).toBeVisible();
    await page.goto("/opportunities#closing");
    await expect(page.getByText(/Satıcı karşı teklifi:.*4.800.000/)).toBeVisible();
    await expect(page.getByText(/Alıcı teklifi:.*4.500.000/)).toBeVisible();
    await expect(page.getByText(/Liste fiyatı:.*5.000.000/)).toBeVisible();
    await expect(page.getByText("Randevu planı; karşı tarafın teyidi bekleniyor.")).toBeVisible();
    const journeys = page.getByLabel("İş yolu", { exact: true });
    const outcomes = page.getByLabel("Fırsat durumu", { exact: true });
    const headerAdvance = page.locator(".page-header").getByRole("button", { name: /ilerlet/i });
    await expect(headerAdvance).toHaveText("Melis Şaşmaz: ilerlet");
    await expect(journeys.getByRole("button", { name: "Tümü 2", exact: true })).toBeVisible();
    await expect(journeys.getByRole("button", { name: "Portföy kazanma 1", exact: true })).toBeVisible();
    await expect(journeys.getByRole("button", { name: "Müşteri talepleri 1", exact: true })).toBeVisible();
    await expect(outcomes.getByRole("button", { name: "Açık · 1", exact: true })).toBeVisible();
    await expect(outcomes.getByRole("button", { name: "Kazanılan · 1", exact: true })).toBeVisible();
    await outcomes.getByRole("button", { name: "Kazanılan · 1", exact: true }).click();
    await expect(headerAdvance).toHaveCount(0);
    await expect(outcomes.getByRole("button", { name: "Açık · 1", exact: true })).toBeVisible();
    await expect(journeys.getByRole("button", { name: "Tümü 2", exact: true })).toBeVisible();
    await expect(page.locator(".opportunity-list-table > button").filter({ hasText: "Anıl Emene" })).toBeVisible();
    await page.locator(".page-header").screenshot({ path: `test-results/won-header-${info.project.name}.png` });
    await outcomes.getByRole("button", { name: "Kaybedilen · 0", exact: true }).click();
    await expect(headerAdvance).toHaveCount(0);
    await outcomes.getByRole("button", { name: "Kazanılan · 1", exact: true }).click();
    await page.getByRole("searchbox", { name: "Fırsatlarda ara", exact: true }).fill("Melis");
    await expect(journeys.getByRole("button", { name: "Tümü 1", exact: true })).toBeVisible();
    await expect(outcomes.getByRole("button", { name: "Kazanılan · 0", exact: true })).toBeVisible();
    await page.getByRole("searchbox", { name: "Fırsatlarda ara", exact: true }).fill("");
    await journeys.getByRole("button", { name: "Portföy kazanma 1", exact: true }).click();
    await expect(outcomes.getByRole("button", { name: "Açık · 0", exact: true })).toBeVisible();
    await expect(outcomes.getByRole("button", { name: "Kazanılan · 1", exact: true })).toBeVisible();
    await outcomes.getByRole("button", { name: "Açık · 0", exact: true }).click();
    await expect(headerAdvance).toHaveCount(0);
    await journeys.getByRole("button", { name: "Tümü 2", exact: true }).click();
    await outcomes.getByRole("button", { name: "Açık · 1", exact: true }).click();
    await expect(headerAdvance).toHaveText("Melis Şaşmaz: ilerlet");
    await page.getByRole("searchbox", { name: "Fırsatlarda ara", exact: true }).fill("Anıl");
    await expect(headerAdvance).toHaveCount(0);
    await page.getByRole("searchbox", { name: "Fırsatlarda ara", exact: true }).fill("");
    await page.getByRole("combobox", { name: "Fırsat türü", exact: true }).selectOption("seller_listing");
    await expect(headerAdvance).toHaveCount(0);
    await page.getByRole("combobox", { name: "Fırsat türü", exact: true }).selectOption("all");
    const appointmentStage = page.getByRole("region", { name: "Yolun neresinde" }).getByRole("button", { name: /Randevu/ });
    await appointmentStage.click();
    await expect(headerAdvance).toHaveCount(0);
    await appointmentStage.click();
    await expect(headerAdvance).toHaveText("Melis Şaşmaz: ilerlet");
    await headerAdvance.click();
    await expect(page.getByRole("dialog").getByRole("heading", { name: "Melis Şaşmaz", exact: true })).toBeVisible();
    await page.getByRole("dialog").getByRole("button", { name: "Kapat", exact: true }).click();

    const workRow = page.locator(".work-row").filter({ hasText: "Melis Şaşmaz" });
    const matchIndicator = workRow.getByRole("button", { name: "Melis Şaşmaz: 1 portföy adayı · Bilgi eksik. Portföyleri incele", exact: true });
    await expect(matchIndicator).toBeVisible();
    await matchIndicator.click();
    const matchesDialog = page.getByRole("dialog", { name: "Melis Şaşmaz", exact: true });
    await expect(matchesDialog.getByRole("heading", { name: "Bu talebe uygun portföyler", exact: true })).toBeVisible();
    await expect(matchesDialog).toContainText("Kadıovacık 620 m² arsa");
    await expect(matchesDialog).toContainText("Bilgi eksik; bilinen kriterlerde çelişki yok.");
    await expect(matchesDialog.getByText("FIRSAT DETAYI", { exact: true })).toHaveCount(0);
    await page.screenshot({ path: `test-results/match-shortcut-${info.project.name}.png` });
    await matchesDialog.getByRole("button", { name: "Kapat", exact: true }).click();
    await expect(matchIndicator).toBeFocused();

    await outcomes.getByRole("button", { name: "Kazanılan · 1", exact: true }).click();
    await expect(page.getByRole("button", { name: /Portföyleri incele/ })).toHaveCount(0);
    await outcomes.getByRole("button", { name: "Açık · 1", exact: true }).click();
    await expect(matchIndicator).toBeVisible();
    const editButton = workRow.getByRole("button", { name: "Aksiyonu düzenle / ertele", exact: true });
    await expect(editButton).toHaveText("Düzenle");
    const editBox = await editButton.boundingBox();
    const advanceBox = await workRow.getByRole("button", { name: "İlerlet", exact: true }).boundingBox();
    expect(Math.abs(editBox!.height - advanceBox!.height)).toBeLessThanOrEqual(1);
    expect(Math.abs(editBox!.y - advanceBox!.y)).toBeLessThanOrEqual(1);
    await editButton.click();
    await expect(page.getByRole("dialog").getByRole("combobox", { name: "Yeni aksiyon", exact: true })).toHaveValue("appointment");
    await page.getByRole("dialog").getByRole("button", { name: "Kapat", exact: true }).click();
    await workRow.screenshot({ path: `test-results/work-row-${info.project.name}.png` });
    await page.screenshot({ path: `test-results/negotiation-${info.project.name}.png`, fullPage: true });
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1);
    expect(overflow).toBe(false);
  } finally { await deleteApp(app); }
});
