import { expect, test } from "@playwright/test";
import { deleteApp, initializeApp } from "firebase/app";
import { connectAuthEmulator, createUserWithEmailAndPassword, getAuth } from "firebase/auth";
import { connectFunctionsEmulator, getFunctions, httpsCallable } from "firebase/functions";

test("hızlı nottan kişi ve talep kaydedilir, alıcı ve satıcı kriterleri ayrılır", async ({ page }, info) => {
  const suffix = `${info.project.name}-${Date.now()}`;
  await page.goto("/");
  await page.getByRole("button", { name: "Yeni misin? Çalışma alanı oluştur" }).click();
  await page.getByLabel("Ad soyad").fill("Deniz Retest");
  await page.getByLabel("E-posta").fill(`audit-ui-${suffix}@example.test`);
  await page.getByLabel("Şifre").fill("Test-Advisor-2026!");
  await page.getByRole("button", { name: "Hesap oluştur" }).click();
  await expect(page.getByRole("heading", { name: "İlk işinle başla" })).toBeVisible();
  await page.getByRole("textbox", { name: "Hızlı not" }).fill("Ayşe Kara bugün aradı. Urla İskele'de bahçeli villa arıyor. Bütçesi 18–35 milyon TL. En az 180 m² olmalı. Yarın 14:00'te aramamı istedi. Telefon: 0555 000 11 22.");
  await page.getByRole("button", { name: "Kaydet", exact: true }).click();
  await expect(page.getByRole("button", { name: "Kişi kaydını tamamla" })).toBeVisible();
  await page.getByRole("button", { name: "Düzenle ve işle" }).click();
  let dialog = page.getByRole("dialog");
  await expect(dialog.getByRole("textbox", { name: "Adı", exact: true })).toHaveValue("Ayşe Kara");
  await expect(dialog.getByLabel("Telefon numarası")).toHaveValue("555 000 11 22");
  await expect(dialog.getByLabel("Sonraki adım tarih ve saat")).toHaveValue(/T14:00$/);
  await expect(dialog.getByRole("spinbutton", { name: "Asgari bütçe", exact: true })).toHaveValue("18000000");
  await expect(dialog.getByRole("spinbutton", { name: "Azami bütçe", exact: true })).toHaveValue("35000000");
  await expect(dialog.getByRole("spinbutton", { name: "Minimum m²", exact: true })).toHaveValue("180");
  await expect(dialog.getByRole("spinbutton", { name: "Maksimum m²", exact: true })).toHaveValue("");
  await dialog.getByRole("spinbutton", { name: "Azami bütçe", exact: true }).fill("");
  await expect(dialog.getByRole("spinbutton", { name: "Asgari bütçe", exact: true })).toHaveValue("18000000");
  await dialog.getByRole("spinbutton", { name: "Azami bütçe", exact: true }).fill("35000000");
  await dialog.getByRole("combobox", { name: "Not türü", exact: true }).selectOption("requirement");
  await dialog.getByRole("button", { name: "Yeni kişiyi burada oluştur" }).click();
  await expect(dialog.getByRole("combobox", { name: "Fırsat türü" })).toHaveCount(0);
  await dialog.getByRole("button", { name: "Kişi, görüşme ve talebi oluştur" }).click();
  await expect(dialog).toBeHidden();
  await page.getByRole("region", { name: "Bugün kaydedilen temaslar" }).getByRole("link").click();
  await expect(page.getByRole("heading", { name: "Ayşe Kara", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Tamamla veya ertele" }).click();
  await page.getByRole("textbox", { name: "Kısa sonuç isteğe bağlı" }).fill("Sentetik takip testi tamamlandı.");
  await page.getByRole("button", { name: "Sonucu kaydet" }).click();
  await expect(page.getByRole("region", { name: "Kişi özeti ve çalışma alanı" })).toContainText("Belirlenmedi");

  await page.goto("/opportunities/");
  const buyerCard = page.locator(".kanban-card").filter({ hasText: "Alıcı talebi" });
  await expect(buyerCard).toContainText("Sonraki aksiyon yok");
  await page.getByRole("button", { name: "Portföy adayları" }).click();
  await expect(buyerCard).toHaveCount(0);
  await page.getByRole("button", { name: "Müşteri talepleri" }).click();
  await buyerCard.click();
  await page.getByRole("button", { name: "Kriterleri düzenle" }).click();
  dialog = page.getByRole("dialog");
  await dialog.getByRole("checkbox", { name: "Bölge olmazsa olmaz" }).check();
  await expect(dialog.getByRole("spinbutton", { name: "Minimum m²", exact: true })).toHaveValue("180");
  await expect(dialog.getByRole("textbox", { name: "Minimum bütçe TRY", exact: true })).toHaveValue("18000000");
  await dialog.getByRole("textbox", { name: "Bölgeler · virgülle ayır" }).press("Enter");
  await expect(dialog).toBeVisible();
  await dialog.getByRole("button", { name: "Kriterleri kaydet" }).click();
  await expect(dialog).toBeHidden();
  await buyerCard.click();
  await page.getByRole("button", { name: "Kriterleri düzenle" }).click();
  await expect(dialog.getByRole("checkbox", { name: "Bölge olmazsa olmaz" })).toBeChecked();
  await expect(dialog.getByRole("spinbutton", { name: "Minimum m²", exact: true })).toHaveValue("180");
  await dialog.getByRole("button", { name: "Kapat" }).click();

  await page.getByRole("button", { name: "Yeni fırsat", exact: true }).click();
  await dialog.getByRole("combobox", { name: "Kişi ara", exact: true }).fill("Ayşe");
  await dialog.getByRole("option", { name: "Ayşe Kara" }).click();
  await dialog.getByRole("combobox", { name: "Fırsat türü", exact: true }).selectOption("seller_listing");
  await dialog.getByRole("button", { name: "Fırsatı oluştur" }).click();
  await expect(dialog).toBeHidden();
  await page.getByRole("button", { name: "Portföy adayları" }).click();
  const ownerCard = page.locator(".kanban-card").filter({ hasText: "Satılık portföy" });
  await ownerCard.click();
  await expect(dialog).not.toContainText("Urla İskele");
  await page.getByRole("button", { name: "Mülk bilgilerini düzenle" }).click();
  await expect(dialog.getByRole("textbox", { name: "Minimum bütçe TRY" })).toHaveCount(0);
  await dialog.getByRole("textbox", { name: "Mülk adresi / bölgesi", exact: true }).fill("Urla Kuşçular");
  await dialog.getByRole("textbox", { name: "Beklenen fiyat TRY", exact: true }).fill("32000000");
  await dialog.getByRole("combobox", { name: "Yetki durumu", exact: true }).selectOption("verbal");
  await dialog.getByRole("textbox", { name: "Satma / kiraya verme nedeni", exact: true }).fill("Daha küçük eve taşınacak");
  await dialog.getByRole("button", { name: "Kriterleri kaydet" }).click();
  await expect(dialog).toBeHidden();
  await ownerCard.click();
  await expect(dialog).not.toContainText("Urla İskele");
  await page.getByRole("button", { name: "Mülk bilgilerini düzenle" }).click();
  await expect(dialog.getByRole("textbox", { name: "Mülk adresi / bölgesi", exact: true })).toHaveValue("Urla Kuşçular");
  await expect(dialog.getByRole("textbox", { name: "Satma / kiraya verme nedeni", exact: true })).toHaveValue("Daha küçük eve taşınacak");
});

test("gönderim açık teyit ister ve terminal kapama yeni aksiyon istemez", async ({ page }, info) => {
  const suffix = `${info.project.name}-${Date.now()}`;
  const email = `closing-ui-${suffix}@example.test`;
  const password = "Test-Advisor-2026!";
  const app = initializeApp({ apiKey: "demo-key", projectId: "spherepath-96ecd", authDomain: "spherepath-96ecd.firebaseapp.com" }, suffix);
  const auth = getAuth(app); connectAuthEmulator(auth, "http://127.0.0.1:9099", { disableWarnings: true });
  const functions = getFunctions(app, "europe-west8"); connectFunctionsEmulator(functions, "127.0.0.1", 5001);
  let counter = 0;
  async function command<T>(name: string, data: unknown): Promise<T> {
    const id = `${suffix}-${++counter}`;
    return (await httpsCallable(functions, name)({ data, requestId: id, commandId: id })).data as T;
  }
  try {
    const credential = await createUserWithEmailAndPassword(auth, email, password);
    await command("bootstrapWorkspace", { displayName: "Kapama Retest" });
    await credential.user.getIdToken(true);
    const { contact } = await command<{ contact: { id: string } }>("createContact", { fullName: "Sentetik Müşteri", phone: "", metAtPlace: "Test", source: "other", role: "buyer" });
    const { listing } = await command<{ listing: { id: string } }>("importExistingListing", { ownerContactId: contact.id, opportunityType: "seller_listing", address: "Sentetik Urla Villa", regionSlug: "Urla", propertyType: "villa", roomCount: 3, areaM2: 200, features: ["garden"], authorizationType: "exclusive", askingPrice: 30_000_000, currency: "TRY", expiresAt: null });
    await command("updateListingReadiness", { listingId: listing.id, evidence: { mandate: "verified", eids: "not_required", media: "ready", processingBasis: "verified" } });
    await command("advanceListing", { listingId: listing.id, toStatus: "active", reason: "Sentetik test hazırlığı" });
    await command("updateContactPrivacy", { contactId: contact.id, coreCrmLegalBasis: "legitimate_interest", noticeStatus: "completed", noticeMethod: "verbal", noticeVersion: "test-v1", marketingConsent: "granted", marketingChannels: ["whatsapp"], iysStatus: "approved", profilingObjection: false });
    const { presentationId } = await command<{ presentationId: string }>("createPresentation", { listingId: listing.id, contactId: contact.id, message: "Sentetik sunum, dış mesaj gönderilmez.", channel: "whatsapp" });
    await command("advancePresentation", { presentationId, toStatus: "user_approved" });
    const { dealId } = await command<{ dealId: string }>("createDeal", { listingId: listing.id, buyerContactId: contact.id, buyerOpportunityId: null, source: "direct_inquiry", sourcePresentationId: null, sourceNote: "Sentetik talep", nextActionType: "call", nextActionAt: Date.now() + 86_400_000 });
    for (const toStage of ["offer", "contract"]) await command("advanceDeal", { dealId, toStage, occurredAt: Date.now() - 60_000, evidenceNote: "Sentetik aşama hazırlığı", nextActionType: "call", nextActionAt: Date.now() + 86_400_000, offerAmount: toStage === "offer" ? 30_000_000 : null, actualAmount: null, commissionAmount: null, currency: toStage === "offer" ? "TRY" : null, lostReason: null });
    await page.goto("/");
    await page.getByLabel("E-posta").fill(email); await page.getByLabel("Şifre").fill(password);
    await page.getByRole("button", { name: "Giriş yap", exact: true }).click();
    await expect(page.getByRole("heading", { name: "Bugün", exact: true })).toBeVisible();
    await page.goto("/closing/");
    await page.getByRole("button", { name: "Gönderimi doğrula", exact: true }).click();
    const dialog = page.getByRole("dialog");
    await expect(dialog.getByRole("button", { name: "Gönderildi olarak kaydet" })).toBeDisabled();
    await expect(dialog).toContainText("Bu işlem mesaj göndermez");
    await dialog.getByRole("button", { name: "Kapat", exact: true }).click();
    await page.getByRole("button", { name: "Aşamayı ilerlet", exact: true }).click();
    await expect(dialog.getByRole("combobox", { name: "Sonraki aksiyon", exact: true })).toHaveCount(0);
    await expect(dialog.getByLabel("Sonraki aksiyon zamanı tarih ve saat")).toHaveCount(0);
    await dialog.getByRole("textbox", { name: "Doğrulama notu", exact: true }).fill("Sentetik kapama kabul testi tamamlandı.");
    await dialog.getByRole("textbox", { name: "Gerçekleşen bedel TRY", exact: true }).fill("30000000");
    await dialog.getByRole("textbox", { name: "Komisyon TRY", exact: true }).fill("600000");
    await dialog.getByRole("button", { name: "Aşamayı kaydet" }).click();
    await expect(dialog).toBeHidden();
    await expect(page.locator(".closing-card").filter({ hasText: "Sentetik kapama kabul testi" })).toContainText("Kapandı");
    await expect(page.locator(".closing-card").filter({ hasText: "Sentetik kapama kabul testi" })).not.toContainText("Sonraki:");
  } finally { await deleteApp(app); }
});
