import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";

test("CSV önizlemesinde kişiler sayfalar arasında çıkarılır, geri eklenir ve yalnızca seçilenler aktarılır", async ({ page }, testInfo) => {
  const run = `${testInfo.project.name}-${Date.now()}`;
  await page.goto("/contact-imports");
  await page.getByRole("button", { name: "Yeni misin? Çalışma alanı oluştur" }).click();
  await page.getByLabel("Ad soyad").fill("Aktarım Danışmanı");
  await page.getByLabel("E-posta").fill(`import-${run}@example.test`);
  await page.getByLabel("Şifre").fill("spherepath-test-123");
  await page.getByRole("button", { name: "Hesap oluştur" }).click();
  await expect(page.getByRole("heading", { name: "Kişileri içeri aktar" })).toBeVisible();
  const csv = 'Name,Phone 1 - Value,E-mail 1 - Value,Notes\nAyşe Aktarım,05321234567,ayse@example.test,"Kadıköy’de 3+1 arıyor.\nEkimde tekrar konuş."\nMehmet Atlanacak,05331234567,,Bu kişi seçilmeyecek' + Array.from({ length: 49 }, (_, index) => `\n${index === 0 ? "" : `Ek Kişi ${index}`},,extra${index}@example.test,`).join('');
  await expect(page.getByText(/En fazla 5\.000 kişi ve 2 MB\./)).toBeVisible();
  await page.getByLabel("CSV dosyası").setInputFiles({ name: "google-contacts.csv", mimeType: "text/csv", buffer: Buffer.from(csv) });
  await page.getByRole("button", { name: "Önizlemeyi hazırla", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Aktarıma hazır", exact: true })).toBeVisible();
  await expect(page.getByRole("checkbox", { name: "Ayşe Aktarım" })).toBeChecked();
  await expect(page.getByRole("checkbox", { name: "Mehmet Atlanacak" })).toBeChecked();
  await expect(page.getByRole("status").filter({ hasText: "50 kişi seçildi" })).toBeVisible();
  await expect(page.getByRole("checkbox", { name: "İsimsiz kişi", exact: true })).toBeDisabled();
  await expect(page.locator(".contact-import-source")).not.toHaveAttribute("open", "");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole("heading", { name: "Aktarıma hazır", exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: testInfo.outputPath("import-redesign.png"), fullPage: false });
  const mehmet = page.locator("section").filter({ has: page.getByRole("checkbox", { name: "Mehmet Atlanacak", exact: true }) });
  await mehmet.getByRole("button", { name: "Aktarımdan çıkar", exact: true }).click();
  await expect(mehmet.getByText("Aktarılmayacak", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Sonraki sayfa", exact: true }).click();
  await expect(page.getByRole("checkbox", { name: "Ek Kişi 48", exact: true })).toBeChecked();
  await page.getByRole("button", { name: "Aktarımdan çıkar", exact: true }).click();
  await expect(page.getByRole("status").filter({ hasText: "48 kişi seçildi · 3 kişi aktarım dışında" })).toBeVisible();
  await page.getByRole("button", { name: "İlk sayfa", exact: true }).click();
  await expect(page.getByRole("checkbox", { name: "Mehmet Atlanacak" })).not.toBeChecked();
  await mehmet.getByRole("button", { name: "Geri ekle", exact: true }).click();
  await expect(page.getByRole("checkbox", { name: "Mehmet Atlanacak" })).toBeChecked();
  await page.getByRole("button", { name: "Tümünü seç", exact: true }).click();
  await expect(page.getByRole("status").filter({ hasText: "50 kişi seçildi" })).toBeVisible();
  await page.getByRole("button", { name: "Seçimi temizle", exact: true }).click();
  await expect(page.getByRole("button", { name: "Seçilenleri aktar", exact: true })).toBeDisabled();
  await page.getByRole("checkbox", { name: "Ayşe Aktarım" }).check();
  const refresh = page.waitForResponse((response) => response.url().includes("getContactImport") && response.ok());
  await page.getByRole("button", { name: "Yenile", exact: true }).click();
  await refresh;
  await expect(page.getByRole("status").filter({ hasText: "1 kişi seçildi · 50 kişi aktarım dışında" })).toBeVisible();
  await expect(page.getByRole("checkbox", { name: "Mehmet Atlanacak" })).not.toBeChecked();
  await page.getByText("Aktarılan notlar", { exact: true }).first().click();
  await expect(page.getByText("Ekimde tekrar konuş.", { exact: false })).toBeVisible();
  const accessibility = await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze();
  expect(accessibility.violations.filter((item) => ["critical", "serious"].includes(item.impact ?? ""))).toEqual([]);
  await page.screenshot({ path: testInfo.outputPath("import-preview.png"), fullPage: false });
  await page.getByRole("button", { name: "Seçilenleri aktar", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Aktarım tamamlandı", exact: true })).toBeVisible({ timeout: 60_000 });
  await expect(page.getByText("51/51 · Eklendi: 1 · Birleştirildi: 0 · Atlandı: 50 · Kontrol gerekli: 0")).toBeVisible();
  await page.getByRole("link", { name: "← Kişiler", exact: true }).click();
  await expect(page.getByText("Ayşe Aktarım", { exact: true }).first()).toBeVisible();
  await expect(page.getByText("Mehmet Atlanacak", { exact: true })).toHaveCount(0);
  await page.getByText("Ayşe Aktarım", { exact: true }).first().click();
  await page.getByRole("button", { name: "Hafıza", exact: true }).click();
  await expect(page.getByText("Ekimde tekrar konuş.", { exact: false })).toBeVisible();
  await expect(page.getByText("Notun yazıldığı tarih bilinmiyor.", { exact: false })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("imported-note.png"), fullPage: true });
});
