"use client";

import { useState } from "react";
import { Archive, Check, MapPin, Mic, Pin, RefreshCw, RotateCcw, Send, Sparkles } from "lucide-react";
import Link from "next/link";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { apiQueryKeys, inboxItemKinds, type InboxItemKind, type InboxItemRecord } from "@spherepath/shared";
import { useSession } from "@/features/auth/resources/session";
import { finishDailyTask, loadTodayOverview, replaceDailyTask } from "@/features/today/resources/today";
import { changeInboxItem, createInboxNote, listInboxItems, undoInboxItem } from "../resources/inbox";
import { AppShell } from "@/shared/ui/AppShell";

const kindLabels: Record<InboxItemKind, string> = { note: "Not", person: "Kişi", property: "Mülk", requirement: "Talep", follow_up: "Takip" };
const messageFrom = (error: unknown) => error instanceof Error ? error.message : "İşlem tamamlanamadı.";

export function FeedView() {
  const { session } = useSession(); const client = useQueryClient(); const [text, setText] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const today = useQuery({ queryKey: apiQueryKeys.todayOverviewPeriod("30d"), queryFn: () => loadTodayOverview("30d") });
  const inbox = useQuery({ queryKey: apiQueryKeys.inboxItems, queryFn: () => listInboxItems(session ?? undefined), enabled: Boolean(session) });
  async function save() { if (!session || !text.trim()) return; setSaving(true); setError(null); try { await client.cancelQueries({ queryKey: apiQueryKeys.inboxItems }); const item = await createInboxNote(session, text.trim()); client.setQueryData<InboxItemRecord[]>(apiQueryKeys.inboxItems, (current = []) => [item, ...current.filter((entry) => entry.id !== item.id)]); setText(""); } catch (next) { setError(messageFrom(next)); } finally { setSaving(false); } }
  async function complete(taskId: string) { if (!session) return; try { await finishDailyTask(session, { taskId, status: "completed", outcomeNote: null, skippedReason: null, rescheduledAt: null, rescheduledActionType: null }); await client.invalidateQueries({ queryKey: apiQueryKeys.todayOverview }); } catch (next) { setError(messageFrom(next)); } }
  async function replace(taskId: string) { if (!session) return; try { await replaceDailyTask(session, taskId); await client.invalidateQueries({ queryKey: apiQueryKeys.todayOverview }); } catch (next) { setError(messageFrom(next)); } }
  async function update(inboxItemId: string, values: { kind?: InboxItemKind; pinned?: boolean; archived?: boolean }) { if (!session) return; try { await changeInboxItem(session, { inboxItemId, ...values }); await client.invalidateQueries({ queryKey: apiQueryKeys.inboxItems }); } catch (next) { setError(messageFrom(next)); } }
  async function undo(inboxItemId: string) { if (!session) return; try { await undoInboxItem(session, inboxItemId); await Promise.all([client.invalidateQueries({ queryKey: apiQueryKeys.inboxItems }), client.invalidateQueries({ queryKey: apiQueryKeys.contacts })]); } catch (next) { setError(messageFrom(next)); } }
  return <AppShell><div className="feed-view">
    <header className="feed-header"><div><p className="eyebrow">AKIŞ</p><h1>Bugün</h1><p className="context-sentence">Önce beş işini bitir; sonra duyduğun her şeyi tek cümleyle bırak.</p></div><button className="topbar-icon-button" onClick={() => void Promise.all([today.refetch(), inbox.refetch()])} aria-label="Yenile"><RefreshCw size={17} /></button></header>
    <section className="sp-card daily-five" aria-labelledby="daily-five-title"><div className="feed-section-heading"><div><p className="eyebrow">BUGÜNÜN 5&apos;İ</p><h2 id="daily-five-title">Önce bunları bitir</h2></div><span className="period-chip">{today.data?.completedTaskCount ?? 0}/{today.data?.tasks.length ?? 0}</span></div>{today.isPending ? <p className="context-sentence">Plan hazırlanıyor…</p> : today.data?.tasks.length ? <ol>{today.data.tasks.map((task) => <li key={task.id} className={task.resolutionStatus ? "resolved" : ""}><span className="daily-number">{task.resolutionStatus ? <Check size={15} /> : null}</span><span><strong>{task.title}</strong><small>{task.reason}</small></span>{task.resolutionStatus ? null : <span className="daily-actions"><button title="Değiştir" aria-label={`${task.title} görevini değiştir`} onClick={() => void replace(task.id)}><RefreshCw size={16} /></button><button title="Tamamla" aria-label={`${task.title} görevini tamamla`} onClick={() => void complete(task.id)}><Check size={17} /></button></span>}</li>)}</ol> : <p className="context-sentence">Henüz planlanacak iş yok. İlk notunu veya kişini ekle.</p>}</section>
    <section className="sp-card quick-note" aria-labelledby="quick-note-title"><div className="feed-section-heading"><div><p className="eyebrow">HIZLI KAYIT</p><h2 id="quick-note-title">Aklındakini bırak</h2></div><Sparkles size={20} aria-hidden /></div><textarea value={text} onChange={(event) => setText(event.target.value)} placeholder="Örn. Urla'da bahçeli bir ev duydum…" aria-label="Hızlı not" /><div className="quick-note-actions"><Link className="secondary-action" href="/capture"><Mic size={17} /> Sesli anlat</Link><button disabled={!text.trim() || saving} className="primary-action" onClick={() => void save()}><Send size={17} />{saving ? "Kaydediliyor…" : "Kaydet"}</button></div></section>
    {error ? <p className="form-error notice" role="alert">{error}</p> : null}
    <div className="feed-title"><h2>Notların</h2><p className="context-sentence">Yapay zekâ önerir, kontrol sende kalır.</p></div>
    {inbox.isPending ? <p className="context-sentence">Notlar yükleniyor…</p> : inbox.data?.length ? <section className="keep-grid" aria-label="Akış notları">{inbox.data.filter((item) => item.status !== "archived").map((item) => <article key={item.id} className={`sp-card keep-card kind-${item.kind}`}><div className="keep-meta"><select aria-label="Not türü" disabled={item.id.startsWith("queued-")} value={item.kind} onChange={(event) => void update(item.id, { kind: event.target.value as InboxItemKind })}>{inboxItemKinds.map((kind) => <option key={kind} value={kind}>{kindLabels[kind]}</option>)}</select><small>{item.status === "queued" ? "Kuyrukta" : item.status === "needs_review" ? "Kontrol gerekli" : "İşlendi"}</small></div><p>{item.summary}</p>{item.needsLocation ? <div className="location-prompt"><MapPin size={16} /><span>Nerede? Konumu ekleyince eşleştirebilirim.</span></div> : null}{item.id.startsWith("queued-") ? null : <footer><button title={item.pinned ? "Sabitlemeyi kaldır" : "Sabitle"} aria-label={item.pinned ? "Sabitlemeyi kaldır" : "Sabitle"} onClick={() => void update(item.id, { pinned: !item.pinned })}><Pin size={16} fill={item.pinned ? "currentColor" : "none"} /></button>{item.appliedActions.some((action) => action.undoneAt === null) ? <button title="Geri al" aria-label="Uygulamayı geri al" onClick={() => void undo(item.id)}><RotateCcw size={16} /></button> : null}<button title="Arşivle" aria-label="Arşivle" onClick={() => void update(item.id, { archived: true })}><Archive size={16} /></button></footer>}</article>)}</section> : <div className="sp-card empty-state"><p>Henüz not yok. Bir cümle yazman yeterli.</p></div>}
  </div></AppShell>;
}
