export const advisorWorkflowCopy = {
  recordInterest: "Bu portföye ilgiyi kaydet",
  interestNote: "İlgi / talep açıklaması",
  interestHint: "Alıcının bu mülke ilgisini doğrulayarak kaydet. Eşleşme puanı tek başına alıcı ilgisi sayılmaz.",
  interestSaved: "Mülk ilgisi işleme bağlandı. Teklifleri İşler ekranındaki işlemden sürdürebilirsin.",
  editActionShort: "Düzenle",
  editAction: "Aksiyonu düzenle / ertele",
  requirementMatches: "Bu talebe uygun portföyler",
  missingCriteria: "Eşleşme için talebin bölge ve mülk türünü belirt. Bilinmeyen bütçeyi boş bırakabilirsin.",
  noMatches: "Uygun aday bulunamadı. Talep kriterlerini ve portföy bilgilerini kontrol et.",
  matchError: "Eşleşmeler yüklenemedi. Yeniden dene.",
  incompleteMatch: "Bilgi eksik; bilinen kriterlerde çelişki yok.",
  alternativeMatch: "Bazı kriterler farklı; ayrıntıları incele.",
  internalDeal: "Doğrudan talep ve teklif içeride kaydedilebilir. Sunum göndermek için yayın hazırlığını tamamla.",
  offerParty: "Teklifi veren taraf",
  buyerOffer: "Alıcı teklifi",
  sellerOffer: "Satıcı karşı teklifi",
  offerHistory: "Teklif geçmişi",
  addOffer: "Teklif / karşı teklif kaydet",
  noOffers: "Henüz yapılandırılmış teklif kaydı yok.",
  confirmedAppointment: "Randevu karşı tarafça teyit edildi; danışmanın kaydı.",
  pendingAppointment: "Randevu planı; karşı tarafın teyidi bekleniyor.",
} as const;
